export const COMMUNITY = [
  {
    file: 'accessibilitydays.png',
    fileCompr: 'accessibilitydays.webp',
    name: 'AccessibilityDays',
    link: 'https://accessibilitydays.it/2022/it/',
  },
  {
    file: 'codemotion.png',
    fileCompr: 'codemotion.webp',
    name: 'Codemotion',
    link: 'https://www.codemotion.com/',
  },
  {
    file: 'dina.png',
    fileCompr: 'dina.webp',
    name: 'DInA Tech Hub',
    link: 'https://sites.google.com/view/dina-tech-hub',
  },
  {
    file: 'fuzzybrains.png',
    fileCompr: 'fuzzybrains.webp',
    name: 'FuzzyBrains',
    link: 'https://www.fuzzybrains.org/it/',
  },
  {
    file: 'gdgitalia.png',
    fileCompr: 'gdgitalia.webp',
    name: 'GDGItalia',
    link: 'https://developers-it.googleblog.com/2013/01/seguire-gli-eventi-dei-gdg-italiani.html',
  },
  {
    file: 'grusp.png',
    fileCompr: 'grusp.webp',
    name: 'Grusp',
    link: 'https://www.grusp.org/',
  },
  {
    file: 'minotauro.png',
    fileCompr: 'minotauro.webp',
    name: 'Podcast Minotauro',
    link: 'https://open.spotify.com/show/1XaQbngzCCwAnnVM5epDS0',
  },
  {
    file: 'pausacaffe.png',
    fileCompr: 'pausacaffe.webp',
    name: 'Pausa Caffè',
    link: 'https://pausacaffe.live/',
  },
  {
    file: 'pointerpodcast.png',
    fileCompr: 'pointerpodcast.webp',
    name: 'Pointer Podcast',
    link: 'https://pointerpodcast.it/',
  },
  {
    file: 'shetech.png',
    fileCompr: 'shetech.webp',
    name: 'SheTech',
    link: 'https://shetechitaly.org/',
  },
  {
    file: 'superheroesvalley.png',
    fileCompr: 'superheroesvalley.webp',
    name: 'SuperHeroesValley',
    link: 'https://www.superheroesvalley.fun/',
  },
  {
    file: 'theredcode.png',
    fileCompr: 'theredcode.webp',
    name: 'The Red Code',
    link: 'https://www.theredcode.it/',
  },
  {
    file: 'tomorrowdevs.png',
    fileCompr: 'tomorrowdevs.webp',
    name: 'TomorrowDevs',
    link: 'https://www.tomorrowdevs.com/',
  },
  {
    file: 'ugidotnet.png',
    fileCompr: 'ugidotnet.webp',
    name: 'UGIdotNET',
    link: 'https://www.ugidotnet.org/',
  },
  {
    file: 'vuejsitalia.png',
    fileCompr: 'vuejsitalia.webp',
    name: 'Vuejs Italia',
    link: 'https://t.me/vue_ita',
  },
  {
    file: 'womentechmakersitalia.png',
    fileCompr: 'womentechmakersitalia.webp',
    name: 'WomenTechmakers Italia',
    link: 'https://www.facebook.com/WTMItalia/',
  },
]
